baseurl       = "https://data.tomhummel.com/"
languagecode  = "en-us"
title         = "data.tomhummel.com"
uglyurls      = false
# disableKinds  = ["section"]
enableInlineShortcodes = true
enableGitInfo = true
ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
  tag = "tags"

[params]
    Title = "Tom Hummel's Data"
    SiteDescription = "All the data"
    author = "Tom Hummel"
    github_repo = "https://github.com/tphummel/data.tomhummel.com/"

[outputFormats]
  [outputFormats.p8s]
    baseName = 'metrics'
    suffix = 'txt'
    isPlainText = true
    mediaType = 'text/plain'

[outputs]
  home = ['html', 'p8s']